/* Writes the site layout that index.html expects:
     <dst>/data/<collection>.js   one file per collection, each appending to window.vs
     <dst>/css/icons.css          `.icon-<id>` rules
     <dst>/img/icons/<id>.<ext>   sprites too big to keep inline

   Shared by scripts/build-data.js so a regenerated dataset drops straight into place.  */
const fs = require('fs')
const path = require('path')

/* Sprites above this many decoded bytes become files. Below it, a data URI is cheaper
   than a request; above it, they dominate the render-blocking stylesheet. */
const INLINE_LIMIT = 3000

/* `.slot.character > .icon` is 6em square — a sprite scaled past that is clipped. */
const CHARACTER_SLOT_EM = 6

const EXTENSION = { 'image/png': 'png', 'image/webp': 'webp', 'image/gif': 'gif', 'image/jpeg': 'jpg' }

function writeCollections(dst, collections) {
  const dir = path.join(dst, 'data')
  fs.mkdirSync(dir, { recursive: true })
  for (const [name, entries] of Object.entries(collections)) {
    const body = entries.map((entry) => '  ' + JSON.stringify(entry)).join(',\n')
    const header =
      `/* Vampire Survivors — ${name} (${entries.length} entries).\n` +
      `   Generated data; see scripts/build-data.js and README "Adding content by hand". */\n` +
      `window.vs = window.vs || {}\n` +
      `window.vs.${name} = [\n`
    fs.writeFileSync(path.join(dir, `${name}.js`), header + body + '\n]\n')
  }
  return Object.keys(collections).length
}

/* Takes a stylesheet where every icon rule is still a data URI and splits the heavy
   ones out into files. Returns { inline, external, bytesMoved }. */
function writeIcons(dst, cssText, characterIds = new Set()) {
  const cssDir = path.join(dst, 'css')
  const imgDir = path.join(dst, 'img', 'icons')
  fs.mkdirSync(cssDir, { recursive: true })
  fs.mkdirSync(imgDir, { recursive: true })

  const stats = { inline: 0, external: 0, bytesMoved: 0 }
  const lines = []

  for (const line of cssText.split(/\r?\n/)) {
    if (!line.trim()) continue
    const match = line.match(/^\.icon-([^\s{]+) \{\s*background-image: url\("data:([^;]+);base64,([^"]+)"\);(.*)\}\s*$/)
    if (!match) {
      lines.push(line)
      continue
    }
    const [, id, mime, base64, rest] = match
    const buffer = Buffer.from(base64, 'base64')
    const tail = capCharacterSprite(rest.trim(), characterIds.has(id))

    let url
    if (buffer.length > INLINE_LIMIT) {
      const file = `${id}.${EXTENSION[mime] || 'png'}`
      fs.writeFileSync(path.join(imgDir, file), buffer)
      url = `../img/icons/${file}`
      stats.external++
      stats.bytesMoved += buffer.length
    } else {
      url = `data:${mime};base64,${base64}`
      stats.inline++
    }
    lines.push(`.icon-${id} { background-image: url("${url}");${tail ? ' ' + tail : ''} }`)
  }

  const header =
    '/* One rule per item id: `.icon-<id>`.\n' +
    '   Small sprites stay inline as data URIs (no request); anything over ~3 KB lives in\n' +
    '   img/icons/ so this stylesheet does not block first paint. Regenerated by\n' +
    '   scripts/build-data.js — see README. */\n'
  fs.writeFileSync(path.join(cssDir, 'icons.css'), header + lines.join('\n') + '\n')
  return stats
}

/* Character rules carry an explicit background-size so pixel art renders at a constant
   10px-per-em. Boss-sized sprites overflow their slot, so scale those down to fit. */
function capCharacterSprite(tail, isCharacter) {
  if (!isCharacter) return tail
  const size = tail.match(/background-size: ([\d.]+)em ([\d.]+)em;/)
  if (!size) return tail
  const [width, height] = [+size[1], +size[2]]
  const scale = Math.min(1, CHARACTER_SLOT_EM / Math.max(width, height))
  if (scale === 1) return tail
  const fit = (n) => +(n * scale).toFixed(2)
  return tail.replace(size[0], `background-size: ${fit(width)}em ${fit(height)}em;`)
}

module.exports = { writeCollections, writeIcons, INLINE_LIMIT, CHARACTER_SLOT_EM }
